SELECT user_id,
       application_status,
       cv_upload_choice,
       age,
       university,
       graduation_year,
       level_of_study,
       country_of_residence,
       access_requirements,
       ethnicity,
       gender,
       hackathon_experience,
       tshirt_size,
       updated_at,
       application_accepted_at,
       application_status_updated_at,
       application_submitted_at,
       travel_origin
FROM public."UserInfo"
LIMIT 1000;